media:
  input: files/media
  output: /files/media
  
content:
  - name: posts
    label: Posts
    path: content/post
    type: collection

    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc

    fields: 
      - name: title
        type: string
      - name: slug
        type: string
      - name: description
        type: string
      - name: date
        type: date
      - name: draft
        type: boolean
      